### ISSUE TITLE
Parsing fails on Azure Pipelines when job has "matrix"

### ISSUE THREAD

**Issue by tamirkiviti13** [argonsecurity/pipeline-parser#44]
## Description

In Azure Pipelines a job might have a "strategy" key which includes a "matrix" key.
When trying to parse such Azure Pipelines file, it fails with the error "yaml: unmarshal errors:\n line 35: cannot unmarshal !!map into string"

## What did you expect to happen?
The file to be parsed, or at least the key to be ignored

## What happened instead?
The parsing failed with an error

```bash
pipeline-parser --platform azure azure-pipelines.yml
Error: yaml: unmarshal errors:\n line 35: cannot unmarshal !!map into string'
```

## Additional details:
The matrix in the file looks like this:
```yaml
  strategy:
      maxParallel: 2
      matrix:
        ${{ if in(parameters.artifact,'*', 'docker/image') }}:
          docker:
            ArtifactPath: docker/image
        ${{ if in(parameters.artifact,'*', 'docker/tar') }}:
          tar:
            ArtifactPath: docker/tar
        ${{ if in(parameters.artifact,'*', 'go') }}:
          go:
            ArtifactPath: go
        ${{ if in(parameters.artifact,'*', 'java') }}:
          java:
            ArtifactPath: java
        ${{ if in(parameters.artifact,'*', 'node') }}:
          node:
            ArtifactPath: node
        ${{ if in(parameters.artifact,'*', 'php') }}:
          php:
            ArtifactPath: php
        ${{ if in(parameters.artifact,'*', 'python/tar') }}:
          python/tar:
            ArtifactPath: python/tar
        ${{ if in(parameters.artifact,'*', 'python/wheel') }}:
          python/wheel:
            ArtifactPath: python/wheel
```
