### ISSUE TITLE
Azure pipelines - support service integration

### ISSUE THREAD

**Issue by danielciuraru86** [argonsecurity/pipeline-parser#69]
There is an option in Azure to connect orgs using service definitions.
Check if we can integrate and expand pipeline template support.

Example:
```
resources:
  repositories:
  - repository: templates
    name: Contoso/BuildTemplates
    endpoint: myServiceConnection # Azure DevOps service connection
jobs:
- template: common.yml@templates
```
