### ISSUE TITLE
Azure pipelines - support azure to github integration

### ISSUE THREAD

**Issue by danielciuraru86** [argonsecurity/pipeline-parser#70]
There is an option in Azure to connect pipeline template to a github repo.
Check if we can integrate and expand pipeline template support.
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

Example:
```
# Repo: Contoso/WindowsProduct
# File: azure-pipelines.yml
resources:
  repositories:
    - repository: templates
      type: github
      name: Contoso/BuildTemplates
      ref: refs/tags/v1.0 # optional ref to pin to

jobs:
- template: common.yml@templates  # Template reference
  parameters:
    vmImage: 'windows-latest'
```
